import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import * as E from '../src/engine.js';
import * as D from '../src/database.js';
const fixtureDB=JSON.parse(readFileSync(new URL('./fixtures/default-database.json',import.meta.url)));
const read=n=>n==='players'?{schemaVersion:1,players:fixtureDB.players}:fixtureDB[n];
const bundled={clubs:read('clubs'),leagues:read('leagues'),players:read('players').players};
const make=(seed=2026,id='c0',db=bundled)=>E.newGame(seed,id,db);
function completeWeek(s){if(E.nextFixture(s))E.simulateMatch(s,E.startMatch(s));E.finishRound(s);}
function assertEvents(m){for(let side=0;side<2;side++){
  const shots=m.events.filter(e=>e.side===side&&['shot','goal'].includes(e.type));
  assert.equal(shots.length,m.shots[side]);assert.equal(shots.filter(e=>e.goal).length,m.score[side]);assert.equal(shots.filter(e=>e.onTarget).length,m.onTarget[side]);
  assert.ok(Math.abs(shots.reduce((v,e)=>v+e.xg,0)-m.xg[side])<1e-8);
}assert.equal(Object.values(m.goals).reduce((a,b)=>a+b,0),m.score[0]+m.score[1]);assert.equal(m.possessionTicks[0]+m.possessionTicks[1],90);assert.equal(E.possession(m).reduce((a,b)=>a+b),100);}

test('default regression database has valid, independent club and player IDs',()=>{assert.deepEqual(D.validateDatabase(bundled),[]);assert.equal(bundled.clubs.length,12);assert.equal(new Set(bundled.players.map(p=>p.id)).size,264);});
test('schedules adapt to even, odd, and custom team counts / legs',()=>{for(const count of [2,5,8,12,15])for(const legs of [1,2,3,4]){const ids=Array.from({length:count},(_,i)=>`custom-team-${i}`),fs=E.fixtures(ids,1,legs),pairs=new Map();assert.equal(fs.flat().length,count*(count-1)/2*legs);for(const rr of fs){assert.equal(new Set(rr.flatMap(f=>[f.home,f.away])).size,rr.length*2);for(const f of rr){const key=[f.home,f.away].sort().join(':');pairs.set(key,(pairs.get(key)||0)+1);}}assert.ok([...pairs.values()].every(n=>n===legs));if(legs===2)for(const id of ids){assert.equal(fs.flat().filter(f=>f.home===id).length,count-1);assert.equal(fs.flat().filter(f=>f.away===id).length,count-1);}}});
test('seeded event replay and midmatch save resume are exact',()=>{const a=make(),b=make();const ma=E.startMatch(a),mb=E.startMatch(b);for(let i=0;i<30;i++){E.stepMatch(a,ma);E.stepMatch(b,mb);}const reloaded=E.deserialize(E.serialize(b));E.simulateMatch(a,ma);E.simulateMatch(reloaded,reloaded.activeMatch);assert.deepEqual(ma,reloaded.activeMatch);assertEvents(ma);});
test('pause at halftime, tactics and substitutions affect remaining strength and persist',()=>{const s=make(),m=E.startMatch(s),side=m.teams.indexOf(s.userClubId);for(let i=0;i<45;i++)E.stepMatch(s,m);assert.equal(m.phase,'halftime');E.stepMatch(s,m);assert.equal(m.minute,45);const before=E.teamRatings(s,m,side);E.changeMatchTactic(m,side,'mentality','Attacking');assert.ok(E.teamRatings(s,m,side).attack>before.attack);const out=m.lineups[side].find(id=>E.player(s,id).position==='MID'),incoming=m.bench[side].find(id=>E.player(s,id).position==='MID');E.substitute(s,m,side,out,incoming);assert.ok(m.lineups[side].includes(incoming));assert.ok(!m.lineups[side].includes(out));assert.throws(()=>E.substitute(s,m,side,incoming,out));const copy=E.deserialize(E.serialize(s));E.simulateMatch(copy,copy.activeMatch);assert.equal(copy.activeMatch.minutes[incoming],45);assert.equal(copy.activeMatch.minutes[out],45);assertEvents(copy.activeMatch);});
test('entire season: fixtures, standings, player totals, ledger, reloads, and next season',()=>{let s=make();const starting=new Map(s.clubs.map(c=>[c.id,c.balance]));for(let r=0;r<s.fixtures.length;r++){
  completeWeek(s);s=E.deserialize(E.serialize(s));for(const c of s.clubs)assert.equal(c.balance,starting.get(c.id)+c.income-c.expenses);
}const fs=s.fixtures.flat(),table=E.standings(s);assert.equal(fs.length,132);assert.ok(fs.every(f=>f.result));assert.ok(table.every(c=>c.played===22));assert.equal(table.reduce((n,c)=>n+c.gf,0),table.reduce((n,c)=>n+c.ga,0));assert.equal(s.players.reduce((n,p)=>n+p.goals,0),fs.reduce((n,f)=>n+f.result.score[0]+f.result.score[1],0));assert.equal(s.players.reduce((n,p)=>n+p.shots,0),fs.reduce((n,f)=>n+f.result.shots[0]+f.result.shots[1],0));assert.equal(table.reduce((n,c)=>n+c.points,0),fs.reduce((n,f)=>n+(f.result.score[0]===f.result.score[1]?2:3),0));const balances=s.clubs.map(c=>c.balance);assert.throws(()=>E.finishRound(s));E.nextSeason(s);assert.equal(s.season,2);assert.equal(s.round,0);assert.equal(s.history.length,1);assert.deepEqual(s.clubs.map(c=>c.balance),balances);assert.ok(s.players.every(p=>!p.goals&&!p.appearances&&p.contract>0));assert.doesNotThrow(()=>E.deserialize(E.serialize(s)));completeWeek(s);});
test('odd-team custom league completes byes and a full season',()=>{const db=structuredClone(bundled);db.clubs=db.clubs.slice(0,5);db.leagues[0].teamIds=db.clubs.map(c=>c.id);db.players=db.players.filter(p=>db.leagues[0].teamIds.includes(p.clubId));const s=make(17,'c2',db);while(s.round<s.fixtures.length)completeWeek(s);assert.ok(E.standings(s).every(c=>c.played===8));assert.equal(s.fixtures.flat().length,20);assert.doesNotThrow(()=>E.deserialize(E.serialize(s)));});
test('transfer conservation, rejected negotiations, wages and ownership',()=>{const s=make(),p=s.players.find(p=>p.clubId==='c1'&&p.position==='MID'),buyer=E.club(s,s.userClubId),seller=E.club(s,p.clubId),fee=Math.ceil(E.askingPrice(p)*1.2),wage=p.wage*2,total=s.clubs.reduce((a,c)=>a+c.balance,0),beforeB=buyer.balance,beforeS=seller.balance;const result=E.transfer(s,p.id,fee,wage,3);assert.equal(result.ok,true);assert.equal(p.clubId,buyer.id);assert.equal(p.wage,wage);assert.equal(p.contract,3);assert.equal(buyer.balance,beforeB-fee);assert.equal(seller.balance,beforeS+fee);assert.equal(s.clubs.reduce((a,c)=>a+c.balance,0),total);assert.equal(s.players.filter(x=>x.id===p.id).length,1);const rejected=s.players.find(p=>p.clubId==='c2'&&p.position==='MID');const snapshot=s.clubs.map(c=>c.balance);assert.equal(E.transfer(s,rejected.id,0,100,3).ok,false);assert.deepEqual(s.clubs.map(c=>c.balance),snapshot);assert.throws(()=>E.transfer(s,rejected.id,E.askingPrice(rejected)*2,rejected.wage*2,3),/already negotiated/);assert.doesNotThrow(()=>E.deserialize(E.serialize(s)));});
test('sales, scouting, and contract renewal persist with balanced accounting',()=>{const s=make(),p=s.players.find(p=>p.clubId===s.userClubId&&p.position==='MID'),total=s.clubs.reduce((n,c)=>n+c.balance,0);E.sellPlayer(s,p.id);assert.notEqual(p.clubId,s.userClubId);assert.equal(s.clubs.reduce((n,c)=>n+c.balance,0),total);const c=E.club(s,s.userClubId),cash=c.balance;E.scout(s,p.id);assert.equal(c.balance,cash-s.league.transferRules.scoutingCost);E.scout(s,p.id);assert.equal(c.balance,cash-s.league.transferRules.scoutingCost);const own=E.squad(s,c.id)[0];E.renewContract(s,own.id,4,own.wage*2);assert.equal(own.contract,4);assert.doesNotThrow(()=>E.deserialize(E.serialize(s)));});
test('actual technical, physical, mental and goalkeeper attributes drive strength',()=>{const s=make(),m=E.startMatch(s),side=m.teams.indexOf(s.userClubId),base=E.teamRatings(s,m,side);for(const id of m.lineups[side]){const p=E.player(s,id);for(const key of D.ALL_ATTRIBUTES)p[key]=99;}const high=E.teamRatings(s,m,side);assert.ok(high.attack>base.attack);assert.ok(high.defense>base.defense);assert.ok(high.control>base.control);assert.ok(high.gk>base.gk);});
test('strong teams usually outperform weak teams but draws and upsets remain',()=>{let strongWins=0,weakWins=0,draws=0;for(let seed=1;seed<=150;seed++){const s=make(seed);const m=E.createMatch(s,{id:'calibration',home:'c0',away:'c11'});E.simulateMatch(s,m);assertEvents(m);if(m.score[0]>m.score[1])strongWins++;else if(m.score[0]<m.score[1])weakWins++;else draws++;}console.log({strongWins,weakWins,draws});assert.ok(strongWins>weakWins*1.4);assert.ok(weakWins>0);assert.ok(draws>0);});
test('CSV and JSON roundtrips preserve attributes, IDs, foot and secondary positions',()=>{const players=structuredClone(bundled.players);players[0].name='Luca, "The Wall"\nVale';players[0].secondaryPositions=['CB'];assert.deepEqual(D.importCSV(D.exportCSV(players)).map(D.normalizePlayer),players.map(p=>Object.fromEntries(Object.entries(D.normalizePlayer(p)).filter(([k])=>D.CSV_COLUMNS.includes(k)||k==='position'))));const json=D.parsePlayerJSON(D.playerJSON(players));assert.deepEqual(D.validatePlayers(json,bundled.clubs),[]);assert.deepEqual(json,players.map(D.normalizePlayer));});
test('database rejects duplicates, missing fields, unknown clubs and invalid ratings',()=>{const ps=structuredClone(bundled.players.slice(0,2));ps[1].id=ps[0].id;ps[0].name='';ps[0].clubId='missing-club';ps[0].passing=100;const errors=D.validatePlayers(ps,bundled.clubs).join(' ');for(const term of ['duplicate ID','name','unknown club','passing'])assert.match(errors,new RegExp(term));assert.throws(()=>D.importCSV('name,age\nBad,99'),/Missing CSV columns/);assert.throws(()=>D.importCSV('"id,name\na,b'),/unclosed/);});
test('attribute generator works on every position and guards ranges',()=>{for(const pos of D.POSITIONS)for(const n of [1,50,99]){const a=D.generateAttributes(n,pos);assert.equal(Object.keys(a).length,D.ALL_ATTRIBUTES.length);assert.ok(Object.values(a).every(v=>Number.isInteger(v)&&v>=1&&v<=99));}assert.ok(D.generateAttributes(70,'GK').keeping>D.generateAttributes(70,'ST').keeping);});
test('existing save preserves its roster; migration is explicit and preseason only',()=>{const s=make(),changed=structuredClone(bundled.players);changed[0].name='Custom Keeper';assert.notEqual(E.deserialize(E.serialize(s)).players[0].name,changed[0].name);E.migratePlayers(s,changed);assert.equal(s.players[0].name,'Custom Keeper');completeWeek(s);assert.throws(()=>E.migratePlayers(s,changed),/first match/);});
test('career edits persist and budgets record exact adjustment',()=>{const s=make(),c=E.club(s,s.userClubId),balance=c.balance;E.editClub(s,c.id,{name:'My Fictional FC',short:'MFC',color:'#12ab34',balance:balance+12345});assert.equal(c.balance,balance+12345);assert.equal(c.income,12345);E.editLeague(s,{name:'Custom Premier',schedule:{format:'round-robin',legs:1}});assert.equal(s.fixtures.length,11);const loaded=E.deserialize(E.serialize(s));assert.equal(loaded.clubs[0].name,'My Fictional FC');assert.equal(loaded.league.name,'Custom Premier');completeWeek(s);assert.throws(()=>E.editLeague(s,{schedule:{format:'round-robin',legs:2}}),/before the first match/);});
test('preseason window and league transfer limits are enforced',()=>{const s=make(),p=s.players.find(p=>p.clubId==='c1'&&p.position==='MID');s.league.transferRules.maxSquad=22;assert.throws(()=>E.transfer(s,p.id,2000000,10000,3),/squad limit/);s.league.transferRules.maxSquad=30;s.league.transferRules.window='preseason';completeWeek(s);assert.throws(()=>E.transfer(s,p.id,2000000,10000,3),/window/);});
test('invalid saves do not get accepted; negative finances can still reload',()=>{const s=make();s.clubs[0].balance=-100;assert.doesNotThrow(()=>E.deserialize(E.serialize(s)));for(const mutate of [s=>s.version=999,s=>s.round=90,s=>s.players[0].passing=100,s=>s.players[1].id=s.players[0].id,s=>s.clubs[0].color='red']){const bad=structuredClone(s);mutate(bad);assert.throws(()=>E.deserialize(E.serialize(bad)));}E.startMatch(s);const bad=structuredClone(s);bad.activeMatch.lineups[0][0]='unknown';assert.throws(()=>E.deserialize(E.serialize(bad)));});
test('injury recovery and training gains advance with actual matchweeks',()=>{const s=make(),c=E.club(s,s.userClubId),injured=E.squad(s,c.id).find(p=>p.position==='DEF'),young=E.squad(s,c.id).find(p=>p.position==='MID');injured.injury=2;injured.fitness=50;E.autoLineup(s,c);young.age=19;young.potential=99;young.development=.95;s.training='Attacking';const keys=['finishing','composure','dribbling','technique'],before=keys.reduce((n,k)=>n+young[k],0);completeWeek(s);assert.equal(injured.injury,1);assert.ok(injured.fitness>50);assert.equal(keys.reduce((n,k)=>n+young[k],0),before+1);completeWeek(s);assert.equal(injured.injury,0);});
test('bookings agree with commentary, match reports, season player totals and saved data',()=>{const s=make();const m=E.startMatch(s);E.simulateMatch(s,m);const cards=m.events.filter(e=>e.type==='card');assert.equal(cards.length,Object.keys(m.cards.yellow).length);assert.ok(cards.every(e=>m.cards.yellow[e.playerId]===1));E.finishRound(s);const playerTotal=s.players.reduce((n,p)=>n+p.yellowCards,0),resultTotal=s.fixtures[0].reduce((n,f)=>n+f.result.yellowCards[0]+f.result.yellowCards[1],0);assert.equal(playerTotal,resultTotal);assert.ok(resultTotal>0);assert.doesNotThrow(()=>E.deserialize(E.serialize(s)));});
