import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
import * as E from '../src/engine.js';import * as A from '../src/assistant.js';
import {PLAYER_ROLES,POSITION_ROLES,roleDefinition} from '../src/roles.js';import {POSITION_SLOTS,tacticalWorkload} from '../src/tactics.js';
import {applyStyle,styleName} from '../src/styles.js';import {shotXG} from '../src/match.js';import {STAT_KEYS,passCompletion} from '../src/statistics.js';
import {postMatchReport} from '../src/assistant-analysis.js';import {assistantProfile} from '../src/migrations.js';
const db=JSON.parse(readFileSync(new URL('./fixtures/default-database.json',import.meta.url)));
const make=(seed=2026)=>E.newGame(seed,'c0',db);
function match(seed=2026){const s=make(seed),m=E.startMatch(s);return {s,m,side:m.teams.indexOf(s.userClubId)};}

test('all positional roles change actual strengths or workload, including keeper and false nine',()=>{
 const {s,m,side}=match();for(const [position,names]of Object.entries(POSITION_ROLES)){
  const p=E.squad(s,s.userClubId).find(p=>p.primaryPosition===position);assert.ok(p,position);
  if(!m.lineups[side].includes(p.id)){const i=POSITION_SLOTS[m.tactics[side].formation].findIndex(pos=>pos===position);m.lineups[side][i>=0?i:5]=p.id;}
  const snapshots=names.map(name=>{m.roles[p.id]=name;m.duties[p.id]=roleDefinition(name).duties.includes('Support')?'Support':roleDefinition(name).duties[0];return JSON.stringify({r:E.teamRatings(s,m,side),work:tacticalWorkload(p,m.tactics[side],name,m.duties[p.id])});});
  assert.equal(new Set(snapshots).size,names.length,`${position}: every role must alter behavior`);
 }
 assert.ok(Object.keys(PLAYER_ROLES).every(name=>Object.values(POSITION_ROLES).some(names=>names.includes(name))));
});
test('duties trade attacking commitment for defensive cover and workload',()=>{const {s,m,side}=match(),id=m.lineups[side].find(id=>E.player(s,id).primaryPosition==='CM');m.roles[id]='Central Midfielder';m.duties[id]='Defend';const defend=E.teamRatings(s,m,side);m.duties[id]='Attack';const attack=E.teamRatings(s,m,side);assert.ok(attack.finishing>defend.finishing);assert.ok(attack.organization<defend.organization);assert.ok(attack.transitionDefense<defend.transitionDefense);});
test('goalkeeper distribution, jumping, work rate and individual decision attributes contribute',()=>{const {s,m,side}=match(),gk=E.player(s,m.lineups[side][0]),p=E.player(s,m.lineups[side][8]);const base=E.teamRatings(s,m,side);gk.distribution=99;gk.goalkeeperPositioning=99;p.jumping=99;p.workRate=99;p.decisions=99;const better=E.teamRatings(s,m,side);assert.ok(better.distribution>base.distribution);assert.ok(better.goalkeeping>base.goalkeeping);assert.ok(better.aerial>base.aerial);assert.ok(better.pressing>base.pressing);});
test('geometric chance quality respects distance, angle, pressure, type and shooter context',()=>{const context={type:'box',distance:14,angle:.2,pressure:.3,source:'buildup',lane:'central',finishing:65};assert.ok(shotXG({...context,distance:11})>shotXG({...context,distance:19}));assert.ok(shotXG({...context,angle:.1})>shotXG({...context,angle:.8}));assert.ok(shotXG({...context,pressure:.1})>shotXG({...context,pressure:.9}));assert.ok(shotXG({...context,finishing:99})>shotXG({...context,finishing:20}));for(const [type,lo,hi,distance]of [['long',.02,.08,28],['box',.08,.25,15],['good',.25,.5,8],['oneOnOne',.3,.6,10],['exceptional',.5,.8,3]]){const x=shotXG({...context,type,distance});assert.ok(x>=lo&&x<=hi,type);}});
test('possessions have real endings and all event statistics agree with player and team totals',()=>{
 const {s,m}=match(42);E.simulateMatch(s,m);assert.ok(m.possessions.some(p=>p.phases.includes('defensive-buildup')));assert.ok(m.possessions.some(p=>p.phases.includes('outcome')));assert.ok(m.possessions.some(p=>p.ending==='foul'));assert.ok(m.possessions.some(p=>p.ending==='tackle'||p.ending==='interception'));
 for(let side=0;side<2;side++){
  const events=m.events.filter(e=>e.side===side),ps=Object.entries(m.playerStats).filter(([id])=>E.player(s,id).clubId===m.teams[side]).map(([,p])=>p);
  for(const [key,type]of [['fouls','foul'],['corners','corner'],['offsides','offside'],['tackles','tackle'],['interceptions','interception'],['highTurnovers','turnover']])assert.equal(m.stats[key][side],events.filter(e=>e.type===type).length,key);
  for(const k of ['passes','completedPasses'])assert.equal(m.stats[k][side],ps.reduce((n,p)=>n+p[k],0),k);
  assert.equal(m.shots[side],ps.reduce((n,p)=>n+p.shots,0));assert.equal(m.onTarget[side],ps.reduce((n,p)=>n+p.onTarget,0));assert.ok(Math.abs(m.xg[side]-ps.reduce((n,p)=>n+p.xg,0))<1e-8);
  assert.equal(m.stats.bigChances[side],events.filter(e=>['goal','shot'].includes(e.type)&&e.xg>=.3).length);
  assert.equal(m.stats.yellowCards[side],events.filter(e=>e.type==='card'&&(e.card==='yellow'||e.secondYellow)).length);
  assert.equal(m.stats.redCards[side],events.filter(e=>e.type==='card'&&e.card==='red').length);
  assert.ok(passCompletion(m,side)>=0&&passCompletion(m,side)<=100);
 }assert.ok(STAT_KEYS.every(k=>m.stats[k].length===2));
});
test('a high press wins more high turnovers against weak buildup while using more fitness',()=>{
 let high=0,low=0,highFit=0,lowFit=0;for(let seed=1;seed<=40;seed++){const {s,m,side}=match(seed);for(const id of m.lineups[1-side]){const p=E.player(s,id);p.passing=40;p.decisions=40;p.firstTouch=40;}m.tactics[1-side]={...m.tactics[1-side],buildup:'Play Out Of Defense',passing:'Short'};
  for(const press of ['Very High','Low']){const x=structuredClone(m);x.tactics[side]={...x.tactics[side],pressing:press,loss:press==='Very High'?'Counter-Press':'Regroup'};for(let i=0;i<40;i++)E.stepMatch(s,x);if(press==='Very High'){high+=x.stats.highTurnovers[side];highFit+=x.fitness[x.lineups[side].filter(Boolean)[5]];}else{low+=x.stats.highTurnovers[side];lowFit+=x.fitness[x.lineups[side].filter(Boolean)[5]];}}
 }assert.ok(high>low+20,{high,low});assert.ok(highFit<lowFit);
});
test('direct passing trades completion for relief from buildup pressure',()=>{let short=0,direct=0,shortCompletion=0,directCompletion=0;for(let seed=1;seed<=35;seed++){const {s,m,side}=match(seed);m.tactics[1-side].pressing='Very High';for(const id of m.lineups[side]){const p=E.player(s,id);p.passing=45;p.vision=45;p.decisions=45;}
 for(const passing of ['Much Shorter','Very Direct']){const x=structuredClone(m);x.tactics[side].passing=passing;for(let i=0;i<35;i++)E.stepMatch(s,x);if(passing==='Much Shorter'){short+=x.stats.buildupLosses[side];shortCompletion+=passCompletion(x,side);}else{direct+=x.stats.buildupLosses[side];directCompletion+=passCompletion(x,side);}}
 }assert.ok(short>direct);assert.ok(shortCompletion>directCompletion);
});
test('fresh substitutions and live roles affect only the remaining match and survive reload',()=>{const {s,m,side}=match();for(let i=0;i<30;i++)E.stepMatch(s,m);const past=structuredClone(m.events),out=m.lineups[side].filter(Boolean).find(id=>E.player(s,id).position==='MID'),incoming=m.bench[side].find(id=>E.player(s,id).position==='MID');m.fitness[out]=25;const tired=E.teamRatings(s,m,side);E.substitute(s,m,side,out,incoming);assert.ok(E.teamRatings(s,m,side).midfield>tired.midfield);const p=E.player(s,incoming),role=POSITION_ROLES[p.primaryPosition].find(n=>n!==m.roles[incoming])||m.roles[incoming],duty=roleDefinition(role).duties[0];E.changeMatchRole(s,m,side,incoming,role,duty);assert.deepEqual(m.events.slice(0,past.length),past);const loaded=E.deserialize(E.serialize(s));assert.equal(loaded.activeMatch.roles[incoming],role);E.simulateMatch(s,m);E.simulateMatch(loaded,loaded.activeMatch);assert.deepEqual(m,loaded.activeMatch);assert.equal(m.minutes[out],30);assert.equal(m.minutes[incoming],60);});
test('red cards remove players, reduce organization, cannot be substituted and cause a served suspension',()=>{let found;for(let seed=1;seed<60&&!found;seed++){const q=match(seed);q.m.tactics.forEach(t=>{t.tackling='Get Stuck In';t.pressing='Very High';});q.s.players.forEach(p=>p.aggression=99);for(let i=0;i<90&&!q.m.done;i++){E.resumeMatch(q.m);E.stepMatch(q.s,q.m);if(q.m.cards.red.length){found=q;break;}}}assert.ok(found);const {s,m}=found,id=m.cards.red[0],side=m.teams.indexOf(E.player(s,id).clubId);assert.ok(!m.lineups[side].includes(id));assert.ok(m.lineups[side].includes(null));assert.throws(()=>E.substitute(s,m,side,id,m.bench[side][0]));assert.doesNotThrow(()=>E.deserialize(E.serialize(s)));E.simulateMatch(s,m);E.finishRound(s);assert.equal(E.player(s,id).suspension,1);assert.equal(E.player(s,id).redCards,1);assert.ok(!E.club(s,m.teams[side]).lineup.includes(id));if(E.nextFixture(s))E.simulateMatch(s,E.startMatch(s));E.finishRound(s);assert.equal(E.player(s,id).suspension,0);});
test('familiarity grows gradually and dramatic changes give a mild temporary organization penalty',()=>{const {s,m,side}=match(),c=E.club(s,s.userClubId),before=c.familiarity.formations['4-3-3'];const base=E.teamRatings(s,m,side).organization;E.changeMatchTactic(m,side,'formation','4-4-2');assert.ok(m.disruption[side]>0&&m.disruption[side]<=.07);const penalty=m.disruption[side];for(let i=0;i<10;i++)E.stepMatch(s,m);assert.ok(m.disruption[side]<penalty);E.changeMatchTactic(m,side,'formation','4-3-3');E.simulateMatch(s,m);E.finishRound(s);assert.ok(c.familiarity.formations['4-3-3']>before);assert.ok(base>0);assert.ok(Object.keys(c.familiarity.styles).length);});
test('assistant preview uses recorded opponent statistics and does not invent an early sample',()=>{const s=make(),before=A.preMatchBriefing(s);assert.ok(before.length>=2&&before.length<=5);assert.match(before.find(a=>a.id==='opponent').reason,/No recorded match sample/);E.simulateMatch(s,E.startMatch(s));E.finishRound(s);const advice=A.assistantAdvice(s).find(a=>a.id==='opponent');assert.match(advice.reason,/Last 1 recorded matches/);assert.match(advice.reason,/Average possession/);assert.match(advice.reason,/Conceded shot origins/);const frozen=JSON.stringify(A.assistantAdvice(s));for(const p of s.players)if(p.clubId!==s.userClubId)p.potential=99;assert.equal(JSON.stringify(A.assistantAdvice(s)),frozen);});
test('assistant uses actual high turnovers, flank progression, ratings and bookings with exact apply/ignore',()=>{const {s,m,side}=match();m.minute=48;m.tactics[side].buildup='Play Out Of Defense';m.tactics[side].defensiveWidth='Narrow';m.stats.highTurnovers[1-side]=5;m.stats.leftAttacks[1-side]=15;m.stats.rightAttacks[1-side]=12;m.stats.centralAttacks[1-side]=3;const cash=s.clubs.map(c=>c.balance);let advice=A.assistantAdvice(s);assert.ok(advice.some(a=>a.id==='buildup-pressure'));assert.ok(advice.some(a=>a.id==='flanks'));const rec=advice.find(a=>a.id==='buildup-pressure');assert.ok(A.recommendationPlan(s,rec).some(t=>t.includes('Direct From Defense')));A.applyRecommendation(s,rec);assert.equal(m.tactics[side].buildup,'Direct From Defense');assert.deepEqual(s.clubs.map(c=>c.balance),cash);const id=m.lineups[side].filter(Boolean).find(id=>E.player(s,id).position==='MID');m.playerStats[id]={rating:5.5};m.minute=60;m.cards.yellow[id]=1;m.tactics[side].pressing='High';advice=A.assistantAdvice(s);const sub=advice.find(a=>a.id==='substitution');assert.ok(sub);assert.match(sub.reason,/rating 5.5/);assert.equal(sub.action.outId,id);A.ignoreRecommendation(s,'substitution');assert.ok(!A.liveRecommendations(s).some(a=>a.id==='substitution'));assert.equal(m.subs[side],0);});
test('assistant can recommend and apply a formation and a position-appropriate creative role',()=>{const {s,m,side}=match();m.minute=40;m.tactics[side].formation='4-3-3';m.tactics[1-side].formation='4-2-3-1';m.possessionTicks[side]=12;m.possessionTicks[1-side]=28;m.shots[side]=1;let a=A.assistantAdvice(s),rec=a.find(a=>a.id==='overload');assert.ok(rec);const lineup=[...m.lineups[side]];A.applyRecommendation(s,rec);assert.equal(m.tactics[side].formation,'4-2-3-1');assert.deepEqual(m.lineups[side],lineup);a=A.assistantAdvice(s);rec=a.find(a=>a.id==='creative-role');assert.ok(rec);A.applyRecommendation(s,rec);assert.equal(m.roles[rec.action.playerId],rec.action.role);assert.equal(m.duties[rec.action.playerId],'Support');});
test('assistant profile is seeded, bounded, visible data and reports cite actual events',()=>{assert.deepEqual(assistantProfile(17),assistantProfile(17));assert.notDeepEqual(assistantProfile(17),assistantProfile(18));const {s,m}=match();for(const key of ['tacticalKnowledge','playerEvaluation','motivating','judgingAbility'])assert.ok(s.assistant.profile[key]>=1&&s.assistant.profile[key]<=20);E.simulateMatch(s,m);const report=postMatchReport(s,m);assert.ok(report.worked.includes('xG'));assert.ok(report.keyPlayer.includes('match rating'));assert.ok(report.tacticalIssue);E.finishRound(s);assert.deepEqual(postMatchReport(s,s.lastMatch),report);for(const [id,stats]of Object.entries(m.playerStats))if(m.minutes[id]>0)assert.equal(E.player(s,id).form.at(-1),Number(stats.rating.toFixed(1)));assert.deepEqual(E.deserialize(E.serialize(s)).assistant.profile,s.assistant.profile);});
test('version 1 migration preserves identities, finance, completed results and active substitutions',()=>{
 const {s,m,side}=match();for(let i=0;i<20;i++)E.stepMatch(s,m);const out=m.setPieces[side],p=E.player(s,out),incoming=m.bench[side].find(id=>E.player(s,id).position===p.position);if(incoming)E.substitute(s,m,side,out,incoming);
 const legacy=structuredClone(s);legacy.version=1;delete legacy.difficulty;delete legacy.assistant;delete legacy.lastMatch;
 for(const c of legacy.clubs){delete c.familiarity;delete c.takers;for(const key of ['freedom','finalThird','buildup','overlapLeft','overlapRight','loss','win','distribution','defensiveWidth','tackling','offsideTrap'])delete c.tactics[key];}
 for(const p of legacy.players){for(const key of ['duty','familiarity','suspension','redCards','workRate','jumping','goalkeeperPositioning','distribution'])delete p[key];}
 for(const key of ['roles','duties','stats','playerStats','statsSinceMinute','takers','disruption','possessions','assistantLive'])delete legacy.activeMatch[key];
 const snapshot={names:legacy.players.map(p=>p.name),cash:legacy.clubs.map(c=>c.balance),score:legacy.activeMatch.score,events:legacy.activeMatch.events,lineups:legacy.activeMatch.lineups};
 const loaded=E.deserialize(JSON.stringify(legacy));assert.equal(loaded.version,2);assert.equal(loaded.difficulty,'Medium');assert.deepEqual(loaded.players.map(p=>p.name),snapshot.names);assert.deepEqual(loaded.clubs.map(c=>c.balance),snapshot.cash);assert.deepEqual(loaded.activeMatch.lineups,snapshot.lineups);assert.deepEqual(loaded.activeMatch.events,snapshot.events);assert.deepEqual(loaded.activeMatch.score,snapshot.score);assert.equal(loaded.activeMatch.statsSinceMinute,20);assert.equal(loaded.activeMatch.takers[side].freeKick,loaded.activeMatch.setPieces[side]);E.simulateMatch(loaded,loaded.activeMatch);E.finishRound(loaded);assert.doesNotThrow(()=>E.deserialize(E.serialize(loaded)));
});
test('save validation rejects corrupt instructions, roles, duties, assistant and event stats',()=>{const {s}=match();for(const mutate of [s=>s.activeMatch.stats.passes=[-1,0],s=>s.activeMatch.duties[s.activeMatch.lineups[0][0]]='Attack',s=>s.activeMatch.tactics[0].loss='nonsense',s=>s.assistant.profile.tacticalKnowledge=99,s=>s.players[0].suspension=-1]){const bad=structuredClone(s);mutate(bad);assert.throws(()=>E.deserialize(E.serialize(bad)));}});

test('an actual save from the previously committed engine preserves its recorded season and resumes',()=>{const text=readFileSync(new URL('./fixtures/legacy-career-v1.json',import.meta.url),'utf8'),old=JSON.parse(text),s=E.deserialize(text);assert.equal(old.version,1);assert.equal(s.version,2);assert.equal(s.players[0].role,'Keeper');assert.equal(s.round,1);assert.equal(s.activeMatch.minute,22);assert.deepEqual(s.fixtures[0].map(f=>f.result.score),old.fixtures[0].map(f=>f.result.score));assert.deepEqual(s.clubs.map(c=>c.balance),old.clubs.map(c=>c.balance));assert.deepEqual(s.activeMatch.lineups,old.activeMatch.lineups);E.simulateMatch(s,s.activeMatch);E.finishRound(s);assert.equal(s.round,2);assert.doesNotThrow(()=>E.deserialize(E.serialize(s)));});
