import {ATTRIBUTES,ALL_ATTRIBUTES,LABELS,POSITIONS,GROUPS,uid,generateAttributes,createDatabasePlayer,validatePlayers,validateDatabase,normalizePlayer,parsePlayerJSON,playerJSON,exportCSV,importCSV} from './database.js';
import {esc,money,crest,option,options,field,numberInput,title,toast,showModal,confirmAction,download,pickFile,errorsHTML,icon} from './ui.js';
const KEY='touchline-database-v1';
let db,bundled,refresh,useDatabase,migrate,tab='players',page=0,search='',clubFilter='',posFilter='',ageFilter='',sort='overall-desc',importErrors=[];
export function initEditor(defaultDB,onRefresh,onUse,onMigrate) {
  bundled=structuredClone(defaultDB);db=structuredClone(defaultDB);refresh=onRefresh;useDatabase=onUse;migrate=onMigrate;
  try{const saved=localStorage.getItem(KEY);if(saved){const parsed=JSON.parse(saved),errors=validateDatabase(parsed);if(errors.length)throw Error(errors[0]);db={...parsed,players:parsed.players.map(normalizePlayer)};}}catch(e){toast(`Editor storage could not load: ${e.message}. The bundled database is available.`,true);}
}
export function getEditorDatabase(){return structuredClone(db);}
function persist(){try{localStorage.setItem(KEY,JSON.stringify(db));toast('Database saved locally.');}catch{toast('Database could not be saved locally. Export JSON to keep your work.',true);}refresh();}
export function renderEditor(hasCareer=false){
  const heading=`<div class="page-heading"><div><div class="eyebrow">Your football world</div><h1>Database studio</h1><p>Build your roster. Shape your league. Every record has a stable ID.</p></div><div class="db-status"><span class="save-dot"></span>Local database · ${db.players.length} players</div></div>`;
  const tabs=`<div class="league-tabs">${['players','clubs','leagues'].map(t=>`<button class="tab ${t===tab?'active':''}" data-editor-tab="${t}">${title(t)}</button>`).join('')}</div>`;
  const actions=`<div class="notice">Edits are saved in this browser, separately from your career. New careers use the bundled files unless you select your edited database. ${hasCareer?'An existing career changes only through explicit migration.':''}</div><div class="toolbar"><button class="btn primary" data-editor-action="use">Use for next career ${icon('arrow')}</button>${hasCareer?'<button class="btn" data-editor-action="migrate">Migrate into career…</button>':''}<button class="btn ghost" data-editor-action="reset">Reset editor to bundled…</button><button class="btn ghost" data-editor-action="files">Export clubs & leagues</button></div>`;
  return `<div class="editor-page">${heading}${actions}${tabs}${importErrors.length?errorsHTML(importErrors):''}${tab==='players'?renderPlayers():tab==='clubs'?renderClubs():renderLeagues()}<p class="help">Bundle your players by replacing <code>data/players.json</code> with your exported JSON. No build is required for this static game. Existing saves keep their own players. See README.md for CSV columns and publishing.</p></div>`;
}
function filtered(){let rows=db.players.filter(p=>(!search||`${p.name} ${p.id} ${p.nationality}`.toLowerCase().includes(search.toLowerCase()))&&(!clubFilter||p.clubId===clubFilter)&&(!posFilter||p.primaryPosition===posFilter||p.secondaryPositions.includes(posFilter))&&(!ageFilter||p.age<=Number(ageFilter)));
  const [key,dir]=sort.split('-');rows.sort((a,b)=>(key==='clubId'?db.clubs.find(c=>c.id===a.clubId).name.localeCompare(db.clubs.find(c=>c.id===b.clubId).name):typeof a[key]==='string'?a[key].localeCompare(b[key]):a[key]-b[key])*(dir==='desc'?-1:1)||a.id.localeCompare(b.id));return rows;}
function renderPlayers(){const rows=filtered(),pages=Math.max(1,Math.ceil(rows.length/40));page=Math.min(page,pages-1);
  return `<div class="toolbar"><input id="db-search" aria-label="Search players" placeholder="Search name, ID, nationality…" value="${esc(search)}"><select id="db-club" aria-label="Filter by club">${option('','All clubs',clubFilter)}${db.clubs.map(c=>option(c.id,c.name,clubFilter)).join('')}</select><select id="db-pos" aria-label="Filter by position">${option('','All positions',posFilter)}${options(POSITIONS,posFilter)}</select><input id="db-age" style="max-width:110px;flex:0" type="number" min="15" max="50" placeholder="Max age" aria-label="Maximum age" value="${esc(ageFilter)}"><select id="db-sort" aria-label="Sort players">${[['overall-desc','Rating ↓'],['overall-asc','Rating ↑'],['age-asc','Age ↑'],['age-desc','Age ↓'],['name-asc','Name A–Z'],['clubId-asc','Club A–Z'],['primaryPosition-asc','Position']].map(([v,t])=>option(v,t,sort)).join('')}</select></div>
  <div class="toolbar"><button class="btn primary" data-editor-action="create-player">+ Create player</button><button class="btn" data-editor-action="import-json">Import JSON</button><button class="btn" data-editor-action="import-csv">Import CSV</button><button class="btn" data-editor-action="export-json">Export JSON</button><button class="btn" data-editor-action="export-csv">Export CSV</button><span class="muted small">Imports replace the editor roster after validation.</span></div>
  <div class="panel"><div class="table-wrap"><table><thead><tr><th>Player / stable ID</th><th>Club</th><th>Position</th><th>Age</th><th>Rating</th><th>Potential</th><th>Actions</th></tr></thead><tbody>${rows.slice(page*40,page*40+40).map(p=>`<tr><td><button class="text-btn" data-edit-player="${esc(p.id)}">${esc(p.name)}</button><div class="tiny muted">${esc(p.id)} · ${esc(p.nationality)}</div></td><td>${esc(db.clubs.find(c=>c.id===p.clubId)?.name)}</td><td><span class="tag">${esc(p.primaryPosition)}</span> <span class="tiny muted">${esc(p.secondaryPositions.join(' / '))}</span></td><td>${p.age}</td><td><span class="number-badge">${p.overall}</span></td><td class="gold">${p.potential}</td><td><div class="editor-actions"><button class="btn sm" data-edit-player="${esc(p.id)}">Edit</button><button class="btn sm" data-duplicate-player="${esc(p.id)}">Duplicate</button><button class="btn sm danger" data-delete-player="${esc(p.id)}">Delete</button></div></td></tr>`).join('')||'<tr><td colspan="7" class="empty">No players match these filters.</td></tr>'}</tbody></table></div><div class="pagination"><span>${rows.length} results · Page ${page+1} of ${pages}</span><div class="actions"><button class="btn sm" data-editor-page="-1" ${page===0?'disabled':''}>Previous</button><button class="btn sm" data-editor-page="1" ${page>=pages-1?'disabled':''}>Next</button></div></div></div>`;
}
function renderClubs(){return `<div class="toolbar"><button class="btn primary" data-editor-action="create-club">+ Create club with cloned squad</button><span class="muted small">League team count follows its club membership; schedules support odd counts and byes.</span></div><div class="club-grid">${db.clubs.map(c=>`<div class="club-card" style="--club-color:${c.color}"><div class="club-card-top">${crest(c,'large')}<div><h2>${esc(c.name)}</h2><p class="tiny">${esc(c.id)} · ${esc(db.leagues.find(l=>l.id===c.leagueId)?.name)}</p></div></div><p>${esc(c.identity)}</p><div class="club-card-meta"><span>${money(c.balance)}</span><strong>${db.players.filter(p=>p.clubId===c.id).length} players</strong></div><div class="actions" style="margin-top:16px"><button class="btn sm" data-edit-club="${esc(c.id)}">Edit club</button><button class="btn sm danger" data-delete-club="${esc(c.id)}">Delete…</button></div></div>`).join('')}</div>`;}
function renderLeagues(){return db.leagues.map(l=>`<div class="panel"><div class="panel-head"><div><h2>${esc(l.name)}</h2><p class="muted small">${esc(l.id)} · ${esc(l.country)} · ${l.teamIds.length} clubs</p></div><button class="btn" data-edit-league="${esc(l.id)}">Edit rules</button></div><div class="panel-body"><div class="grid three"><div><div class="eyebrow">Schedule</div><p>${l.schedule.legs} leg round robin · ${l.teamIds.length%2?'byes included':'balanced fixtures'}</p></div><div><div class="eyebrow">Transfers</div><p>${l.transferRules.window==='always'?'Open all season':'Preseason only'} · ${l.transferRules.maxSquad} squad limit</p></div><div><div class="eyebrow">Movement settings</div><p>${l.promotionRelegation.promote} promotion · ${l.promotionRelegation.relegate} relegation</p></div></div><p class="help">Promotion/relegation settings are saved as extension metadata. Cross-league movement is not activated in this first version.</p></div></div>`).join('');}
export function bindEditor(root){
  root.querySelectorAll('[data-editor-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.editorTab;importErrors=[];refresh();});
  const filters={'db-search':v=>search=v,'db-club':v=>clubFilter=v,'db-pos':v=>posFilter=v,'db-age':v=>ageFilter=v,'db-sort':v=>sort=v};
  for(const [id,set]of Object.entries(filters)){const el=root.querySelector('#'+id);if(el)el.onchange=()=>{set(el.value);page=0;refresh();};}
  root.querySelectorAll('[data-editor-page]').forEach(b=>b.onclick=()=>{page+=Number(b.dataset.editorPage);refresh();});
  root.querySelectorAll('[data-edit-player]').forEach(b=>b.onclick=()=>playerForm(db.players.find(p=>p.id===b.dataset.editPlayer)));
  root.querySelectorAll('[data-duplicate-player]').forEach(b=>b.onclick=()=>{const p=structuredClone(db.players.find(p=>p.id===b.dataset.duplicatePlayer));p.id=uid();p.name+=' copy';playerForm(p,true);});
  root.querySelectorAll('[data-delete-player]').forEach(b=>b.onclick=()=>{const p=db.players.find(p=>p.id===b.dataset.deletePlayer);confirmAction('Delete player?',`${p.name} will be removed from the editor database. Your career is unaffected.`,()=>{db.players=db.players.filter(x=>x.id!==p.id);persist();});});
  root.querySelectorAll('[data-edit-club]').forEach(b=>b.onclick=()=>clubForm(db.clubs.find(c=>c.id===b.dataset.editClub)));
  root.querySelectorAll('[data-delete-club]').forEach(b=>b.onclick=()=>{const c=db.clubs.find(c=>c.id===b.dataset.deleteClub),l=db.leagues.find(l=>l.id===c.leagueId);if(l.teamIds.length<=2)return toast('A league needs at least two clubs.',true);confirmAction('Delete club and its roster?',`${c.name} and its editor players will be removed. Existing careers are unaffected.`,()=>{db.players=db.players.filter(p=>p.clubId!==c.id);db.clubs=db.clubs.filter(x=>x.id!==c.id);l.teamIds=l.teamIds.filter(id=>id!==c.id);persist();});});
  root.querySelectorAll('[data-edit-league]').forEach(b=>b.onclick=()=>leagueForm(db.leagues.find(l=>l.id===b.dataset.editLeague)));
  root.querySelectorAll('[data-editor-action]').forEach(b=>b.onclick=()=>action(b.dataset.editorAction));
}
function action(name){try{
  if(name==='create-player')return playerForm({...createDatabasePlayer(clubFilter||db.clubs[0].id),name:''},true);
  if(name==='export-json')return download('players.json',playerJSON(db.players));
  if(name==='export-csv')return download('players.csv',exportCSV(db.players),'text/csv;charset=utf-8');
  if(name==='files'){download('clubs.json',JSON.stringify(db.clubs,null,2));setTimeout(()=>download('leagues.json',JSON.stringify(db.leagues,null,2)),250);toast('Exported clubs.json and leagues.json. Your browser may ask to allow multiple downloads.');return;}
  if(name==='import-json'||name==='import-csv')return pickFile(name==='import-json'?'.json':'.csv',text=>{
    const players=name==='import-json'?parsePlayerJSON(text):importCSV(text),errors=validatePlayers(players,db.clubs);
    if(errors.length){importErrors=errors;refresh();return toast('Import rejected. Your database was kept; see validation errors.',true);}
    confirmAction('Replace editor roster?',`Import ${players.length} validated players? This replaces the editor roster, while keeping your career. Export your current work first if you need a backup.`,()=>{db.players=players.map(normalizePlayer);importErrors=[];page=0;persist();});
  });
  if(name==='reset')return confirmAction('Reset editor database?', 'All editor changes will be replaced by the bundled database. Your career will remain.',()=>{db=structuredClone(bundled);importErrors=[];page=0;clubFilter='';posFilter='';persist();});
  if(name==='use'){const errors=validateDatabase(db);if(errors.length)throw Error(errors.slice(0,10).join('\n'));useDatabase(getEditorDatabase());return;}
  if(name==='migrate')return confirmAction('Migrate players into this career?', 'Before the first match of a season, this replaces every career player with the matching editor club rosters. Player statistics, injuries, and lineups reset. Career finances and club identities stay. Export your career first to keep a backup.',()=>migrate(db.players));
  if(name==='create-club')return clubForm(null);
}catch(e){toast(e.message,true);}}
function playerForm(source,isNew=false){const p=structuredClone(source);
  const attributes=()=>Object.entries(ATTRIBUTES).map(([category,keys])=>`<section class="attribute-section"><h3>${category}</h3><div class="fields">${keys.map(k=>`<label class="attr-field"><span>${LABELS[k]||title(k)}</span>${numberInput(k,p[k],1,99)}</label>`).join('')}</div></section>`).join('');
  const body=`<form id="player-form"><div class="modal-body"><div id="player-errors"></div><div class="field-grid three">${field('Stable ID',`<input name="id" value="${esc(p.id)}" required ${isNew?'':'readonly'} maxlength="100" pattern="[a-zA-Z0-9_-]+">`)}${field('Player name',`<input name="name" value="${esc(p.name)}" required maxlength="100">`)}${field('Age',numberInput('age',p.age,15,50))}${field('Nationality',`<input name="nationality" value="${esc(p.nationality)}" required maxlength="100">`)}${field('Club',`<select name="clubId">${db.clubs.map(c=>option(c.id,c.name,p.clubId)).join('')}</select>`)}${field('Primary position',`<select name="primaryPosition">${options(POSITIONS,p.primaryPosition)}</select>`)}${field('Preferred foot',`<select name="preferredFoot">${options(['Left','Right','Both'],p.preferredFoot)}</select>`)}${field('Overall rating',numberInput('overall',p.overall,1,99))}${field('Potential',numberInput('potential',p.potential,1,99))}${field('Weekly wage (£)',numberInput('wage',p.wage,100,1000000))}${field('Contract (years)',numberInput('contract',p.contract,1,5))}<div class="field full"><span>Secondary positions</span><div class="checkbox-group">${POSITIONS.map(pos=>`<label><input type="checkbox" name="secondaryPositions" value="${pos}" ${p.secondaryPositions.includes(pos)?'checked':''}>${pos}</label>`).join('')}</div></div></div><div class="toolbar" style="margin-top:20px"><button type="button" class="btn primary" id="generate-attrs">Generate attributes from rating</button><span class="small muted">Uses primary position; replaces individual attributes below.</span></div><div class="attribute-grid">${attributes()}</div><p class="help">Overall is an editor reference rating. Match strength is calculated from your actual attributes. Adjusting individual attributes changes the simulation.</p></div><div class="modal-footer"><button type="button" class="btn" data-form-cancel>Cancel</button><button type="submit" class="btn primary">Save player</button></div></form>`;
  const d=showModal(isNew?'Create player':'Edit player',body);const form=d.querySelector('form');
  form.querySelector('[data-form-cancel]').onclick=()=>d.close();form.querySelector('#generate-attrs').onclick=()=>{const rating=Number(form.elements.overall.value),pos=form.elements.primaryPosition.value;if(!Number.isInteger(rating)||rating<1||rating>99)return toast('Enter a rating from 1–99.',true);const attrs=generateAttributes(rating,pos);for(const k of ALL_ATTRIBUTES)form.elements[k].value=attrs[k];form.elements.potential.value=Math.max(rating,Number(form.elements.potential.value));toast('Position-based attributes generated. You can adjust each one.');};
  form.onsubmit=e=>{e.preventDefault();const fd=new FormData(form),edited={...p};for(const key of ['id','name','nationality','clubId','primaryPosition','preferredFoot'])edited[key]=String(fd.get(key)).trim();for(const k of ['age','overall','potential','wage','contract',...ALL_ATTRIBUTES])edited[k]=Number(fd.get(k));edited.secondaryPositions=fd.getAll('secondaryPositions');edited.position=GROUPS[edited.primaryPosition];
    const index=isNew?-1:db.players.findIndex(x=>x.id===p.id),candidate=[...db.players];if(index<0)candidate.push(edited);else candidate[index]=edited;
    const errors=validatePlayers(candidate,db.clubs);if(errors.length){form.querySelector('#player-errors').innerHTML=errorsHTML(errors);form.querySelector('#player-errors').scrollIntoView({block:'start'});return;}db.players=candidate;d.close();persist();};
}
function clubForm(source){const c=source||{...structuredClone(db.clubs[0]),id:uid('club'),name:'',short:'NEW',balance:2000000,identity:'A new club with a story to write.'};
  const d=showModal(source?'Edit club':'Create club',`<form id="club-form"><div class="modal-body"><div id="club-errors"></div><div class="field-grid">${field('Stable ID',`<input value="${esc(c.id)}" readonly>`)}${field('Name',`<input name="name" value="${esc(c.name)}" required maxlength="60">`)}${field('Abbreviation',`<input name="short" value="${esc(c.short)}" required maxlength="4">`)}${field('Color',`<input name="color" type="color" value="${c.color}">`)}${field('Budget (£)',numberInput('balance',c.balance))}${field('Club strength / reputation',numberInput('strength',c.strength,1,99))}${field('Stadium',`<input name="stadium" value="${esc(c.stadium)}" required maxlength="60">`)}${field('Board expectation',`<select name="expectation">${options(['Win the title','Top 3','Top 6','Top 8','Avoid bottom 2'],c.expectation)}</select>`)}${field('League',`<select name="leagueId">${db.leagues.map(l=>option(l.id,l.name,c.leagueId)).join('')}</select>`)}${!source?field('Clone squad from',`<select name="clone">${db.clubs.map(c=>option(c.id,c.name,db.clubs[0].id)).join('')}</select>`):''}${field('Club identity',`<textarea name="identity" rows="3" maxlength="250">${esc(c.identity)}</textarea>`,'full')}</div><p class="help">Creating a club clones a squad with new unique player IDs. Rename and adjust those players in the player editor. League team count and future career schedules adapt automatically.</p></div><div class="modal-footer"><button type="submit" class="btn primary">Save club</button></div></form>`);
  d.querySelector('form').onsubmit=e=>{e.preventDefault();const fd=new FormData(e.target),updated={...c};for(const k of ['name','short','color','stadium','expectation','leagueId','identity'])updated[k]=String(fd.get(k)).trim();for(const k of ['balance','strength'])updated[k]=Number(fd.get(k));
    const candidate=structuredClone(db);if(source)candidate.clubs[candidate.clubs.findIndex(x=>x.id===c.id)]=updated;else {candidate.clubs.push(updated);candidate.players.push(...db.players.filter(p=>p.clubId===fd.get('clone')).map(p=>({...structuredClone(p),id:uid(),clubId:c.id})));}
    candidate.leagues.forEach(l=>l.teamIds=candidate.clubs.filter(c=>c.leagueId===l.id).map(c=>c.id));const errors=validateDatabase(candidate);if(errors.length){d.querySelector('#club-errors').innerHTML=errorsHTML(errors);return;}db=candidate;d.close();persist();};
}
export function leagueFields(l){const r=l.transferRules,p=l.promotionRelegation;return `<div class="field-grid">${field('League name',`<input name="name" value="${esc(l.name)}" required maxlength="60">`)}${field('Country / region',`<input name="country" value="${esc(l.country)}" maxlength="60">`)}${field('Round-robin legs',`<select name="legs">${[1,2,3,4].map(n=>option(String(n),`${n} (${n%2?'uneven':'equal'} home/away)`,String(l.schedule.legs))).join('')}</select>`)}${field('Transfer window',`<select name="window">${option('always','All season',r.window)}${option('preseason','Before matchweek 1 only',r.window)}</select>`)}${field('Maximum squad size',numberInput('maxSquad',r.maxSquad,11,100))}${field('Minimum squad size',numberInput('minSquad',r.minSquad,11,100))}${field('Minimum goalkeepers retained',numberInput('minKeepers',r.minKeepers,1,10))}${field('Minimum per outfield group retained',numberInput('minOutfieldPerGroup',r.minOutfieldPerGroup,0,20))}${field('Scouting cost (£)',numberInput('scoutingCost',r.scoutingCost))}${field('Wage reserve (weeks)',numberInput('wageReserveWeeks',r.wageReserveWeeks,0,52))}${field('Promotion places (metadata)',numberInput('promote',p.promote,0,l.teamIds.length-1))}${field('Relegation places (metadata)',numberInput('relegate',p.relegate,0,l.teamIds.length-1))}${field('Promotion target league ID',`<input name="promotionTarget" value="${esc(p.promotionTarget||'')}" maxlength="100">`)}${field('Relegation target league ID',`<input name="relegationTarget" value="${esc(p.relegationTarget||'')}" maxlength="100">`)}</div><p class="help">Team count (${l.teamIds.length}) is derived from club membership. This version runs one league per career. Promotion/relegation is stored for future cross-league support, without moving clubs.</p>`;}
export function readLeagueForm(form,l){const fd=new FormData(form);const updated=structuredClone(l);for(const k of ['name','country'])updated[k]=String(fd.get(k)).trim();updated.schedule.legs=Number(fd.get('legs'));updated.transferRules.window=fd.get('window');for(const k of ['maxSquad','minSquad','minKeepers','minOutfieldPerGroup','scoutingCost','wageReserveWeeks'])updated.transferRules[k]=Number(fd.get(k));for(const k of ['promote','relegate'])updated.promotionRelegation[k]=Number(fd.get(k));for(const k of ['promotionTarget','relegationTarget'])updated.promotionRelegation[k]=String(fd.get(k)).trim()||null;return updated;}
function leagueForm(l){const d=showModal('League rules',`<form><div class="modal-body"><div id="league-errors"></div><p class="small muted" style="margin-bottom:20px">Stable league ID: ${esc(l.id)}</p>${leagueFields(l)}</div><div class="modal-footer"><button class="btn primary" type="submit">Save rules</button></div></form>`);d.querySelector('form').onsubmit=e=>{e.preventDefault();const candidate=structuredClone(db);candidate.leagues[candidate.leagues.findIndex(x=>x.id===l.id)]=readLeagueForm(e.target,l);const errors=validateDatabase(candidate);if(errors.length){d.querySelector('#league-errors').innerHTML=errorsHTML(errors);return;}db=candidate;d.close();persist();};}
