import {INSTRUCTION_DEFAULTS} from './tactical-settings.js';
export const TACTICAL_STYLES={
  Balanced:{description:'A measured approach with support in every phase.',suits:'A well-rounded squad without one standout strength.',strengths:'Stable shape and sensible fatigue; adaptable to most opponents.',weaknesses:'Can lack a clear edge against specialist teams.',settings:{mentality:'Balanced',pressing:'Standard',line:'Standard',width:'Balanced',passing:'Mixed',tempo:'Normal'}},
  Possession:{description:'Keep the ball, build patiently, and find support nearby.',suits:'Good passers with strong vision, decisions, and first touch.',strengths:'More control and shorter passing options; limits rushed attacks.',weaknesses:'Creates fewer quick chances and can be slow against a deep defense.',settings:{mentality:'Balanced',pressing:'Standard',line:'Standard',width:'Narrow',passing:'Short',tempo:'Patient'}},
  'High Press':{description:'Win the ball high and attack before the opposition settles.',suits:'Fit players with stamina, pace, and alert defenders.',strengths:'Territory and attacking pressure; forces hurried opponents.',weaknesses:'Faster fatigue and space behind the high line for direct counters.',settings:{mentality:'Attacking',pressing:'High',line:'High',width:'Wide',passing:'Mixed',tempo:'Quick'}},
  Counterattack:{description:'Stay deep, then break forward quickly into open space.',suits:'Quick forwards and defenders who prefer a deeper line.',strengths:'Fast transitions punish high lines and protect slower defenders.',weaknesses:'Concedes possession; struggles when opponents also sit deep.',settings:{mentality:'Cautious',pressing:'Low',line:'Deep',width:'Balanced',passing:'Direct',tempo:'Quick'}},
  'Direct Play':{description:'Move forward early and compete for second balls.',suits:'Strong forwards, good headers, and energetic midfielders.',strengths:'Uses aerial strength; bypasses crowded midfield and short passing pressure.',weaknesses:'Less possession and reliance on physical duels; wastes attacks without suitable forwards.',settings:{mentality:'Balanced',pressing:'Standard',line:'Standard',width:'Wide',passing:'Direct',tempo:'Quick'}},
  Defensive:{description:'Keep a compact shape, take fewer risks, and protect the box.',suits:'Disciplined defenders with positioning and teamwork.',strengths:'More defensive security and recovery; useful when protecting a lead.',weaknesses:'Limited attacking commitment; invites territory and pressure.',settings:{mentality:'Cautious',pressing:'Low',line:'Deep',width:'Narrow',passing:'Short',tempo:'Patient'}}
};
const extra={
 Gegenpress:{description:'Counter-press immediately and move forward quickly.',suits:'Hard workers with stamina, anticipation, and quick defenders.',strengths:'High regains can create chances before the defense settles.',weaknesses:'Heavy workload; failed pressure leaves space behind.',settings:{mentality:'Attacking',pressing:'Very High',line:'High',width:'Wide',passing:'Mixed',tempo:'High',loss:'Counter-Press',win:'Counter',buildup:'Play Out Of Defense',offsideTrap:'On'}},
 'Tiki-Taka':{description:'Short combinations and patient movement through central spaces.',suits:'Excellent technique, first touch, passing, and decisions.',strengths:'Passing support and sustained possession.',weaknesses:'Can be sterile against compact blocks; vulnerable to skilled pressing.',settings:{passing:'Much Shorter',tempo:'Low',width:'Narrow',freedom:'Expressive',finalThird:'Work Ball Into Box',buildup:'Play Out Of Defense',pressing:'High',line:'High',distribution:'Short'}},
 'Counter Attack':{description:'Regroup, then exploit space quickly after regaining the ball.',suits:'Quick attackers and disciplined defenders.',strengths:'Threatens committed opponents without a high line.',weaknesses:'Less effective against low blocks; concedes territory.',settings:{mentality:'Cautious',pressing:'Low',line:'Deep',passing:'More Direct',tempo:'High',loss:'Regroup',win:'Counter',distribution:'Long'}},
 'Wing Play':{description:'Stretch the pitch, overlap, and deliver crosses.',suits:'Good crossers, energetic full backs, and aerial forwards.',strengths:'Can bypass congested central defenses.',weaknesses:'Crosses are less efficient without aerial strength; overlaps expose flanks.',settings:{width:'Wide',defensiveWidth:'Wide',passing:'Mixed',tempo:'High',finalThird:'Early Crosses',overlapLeft:'On',overlapRight:'On'}},
 'Low Block':{description:'Protect the central box with a compact deep shape.',suits:'Positioning, teamwork, and patient defensive organization.',strengths:'Limits central space and protects slower defenders.',weaknesses:'Concedes territory, crosses, and sustained pressure.',settings:{mentality:'Cautious',pressing:'Low',line:'Very Deep',width:'Narrow',defensiveWidth:'Narrow',tackling:'Stay On Feet',loss:'Regroup',win:'Counter',passing:'More Direct',tempo:'Normal'}}
};
Object.assign(TACTICAL_STYLES,extra);
for(const [name,style]of Object.entries(TACTICAL_STYLES)){
 const additions=name==='Possession'?{buildup:'Play Out Of Defense',finalThird:'Work Ball Into Box',distribution:'Short',freedom:'Expressive'}:name==='High Press'?{loss:'Counter-Press',win:'Counter'}:name==='Counterattack'?{win:'Counter',distribution:'Long'}:name==='Direct Play'?{buildup:'Direct From Defense',distribution:'Long',finalThird:'Early Crosses'}:name==='Defensive'?{defensiveWidth:'Narrow',tackling:'Stay On Feet'}:{};
 style.settings={...INSTRUCTION_DEFAULTS,...style.settings,...additions};
}
export function styleName(tactics){return Object.entries(TACTICAL_STYLES).find(([,style])=>Object.entries(style.settings).every(([k,v])=>(tactics[k]??INSTRUCTION_DEFAULTS[k])===v))?.[0]||'Custom';}
export function applyStyle(tactics,name){const style=TACTICAL_STYLES[name];if(!style)throw Error('Unknown tactical style.');return {...tactics,...style.settings};}
