export const TACTICAL_STYLES={
  Balanced:{description:'A measured approach with support in every phase.',suits:'A well-rounded squad without one standout strength.',strengths:'Stable shape and sensible fatigue; adaptable to most opponents.',weaknesses:'Can lack a clear edge against specialist teams.',settings:{mentality:'Balanced',pressing:'Standard',line:'Standard',width:'Balanced',passing:'Mixed',tempo:'Normal'}},
  Possession:{description:'Keep the ball, build patiently, and find support nearby.',suits:'Good passers with strong vision, decisions, and first touch.',strengths:'More control and shorter passing options; limits rushed attacks.',weaknesses:'Creates fewer quick chances and can be slow against a deep defense.',settings:{mentality:'Balanced',pressing:'Standard',line:'Standard',width:'Narrow',passing:'Short',tempo:'Patient'}},
  'High Press':{description:'Win the ball high and attack before the opposition settles.',suits:'Fit players with stamina, pace, and alert defenders.',strengths:'Territory and attacking pressure; forces hurried opponents.',weaknesses:'Faster fatigue and space behind the high line for direct counters.',settings:{mentality:'Attacking',pressing:'High',line:'High',width:'Wide',passing:'Mixed',tempo:'Quick'}},
  Counterattack:{description:'Stay deep, then break forward quickly into open space.',suits:'Quick forwards and defenders who prefer a deeper line.',strengths:'Fast transitions punish high lines and protect slower defenders.',weaknesses:'Concedes possession; struggles when opponents also sit deep.',settings:{mentality:'Cautious',pressing:'Low',line:'Deep',width:'Balanced',passing:'Direct',tempo:'Quick'}},
  'Direct Play':{description:'Move forward early and compete for second balls.',suits:'Strong forwards, good headers, and energetic midfielders.',strengths:'Uses aerial strength; bypasses crowded midfield and short passing pressure.',weaknesses:'Less possession and reliance on physical duels; wastes attacks without suitable forwards.',settings:{mentality:'Balanced',pressing:'Standard',line:'Standard',width:'Wide',passing:'Direct',tempo:'Quick'}},
  Defensive:{description:'Keep a compact shape, take fewer risks, and protect the box.',suits:'Disciplined defenders with positioning and teamwork.',strengths:'More defensive security and recovery; useful when protecting a lead.',weaknesses:'Limited attacking commitment; invites territory and pressure.',settings:{mentality:'Cautious',pressing:'Low',line:'Deep',width:'Narrow',passing:'Short',tempo:'Patient'}}
};
export function styleName(tactics){return Object.entries(TACTICAL_STYLES).find(([,style])=>Object.entries(style.settings).every(([k,v])=>(tactics[k]??(k==='tempo'?'Normal':undefined))===v))?.[0]||'Custom';}
export function applyStyle(tactics,name){const style=TACTICAL_STYLES[name];if(!style)throw Error('Unknown tactical style.');return {...tactics,...style.settings};}
