export const esc = v => String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const money = v => `${v<0?'−':''}£${Math.abs(Math.round(v)).toLocaleString('en-GB')}`;
export const compactMoney = v => `${v<0?'−':''}£${Math.abs(v)>=1e6?(Math.abs(v)/1e6).toFixed(2)+'m':Math.round(Math.abs(v)/1000)+'k'}`;
export const title = v => v.replace(/([A-Z])/g,' $1').replace(/^./,c=>c.toUpperCase());
export const crest = (c,size='') => `<span class="crest ${size}" style="--club-color:${esc(c.color)}" aria-label="${esc(c.name)} crest">${esc(c.short)}</span>`;
export const option = (value,text,selected) => `<option value="${esc(value)}" ${value===selected?'selected':''}>${esc(text)}</option>`;
export const options = (values,selected) => values.map(v=>option(v,v,selected)).join('');
export const field = (label,control,cls='') => `<label class="field ${cls}"><span>${esc(label)}</span>${control}</label>`;
export const numberInput=(name,value,min=0,max=999999999,step=1)=>`<input type="number" name="${esc(name)}" value="${value}" min="${min}" max="${max}" step="${step}" required>`;
export const icon = name => {
  const paths={dashboard:'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',squad:'<circle cx="9" cy="7" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M17 4a3 3 0 0 1 0 6M18 14a5 5 0 0 1 3 5v2"/>',tactics:'<rect x="3" y="2" width="18" height="20" rx="2"/><path d="M3 12h18"/><circle cx="12" cy="12" r="3"/><path d="M8 2v4h8V2M8 22v-4h8v4"/>',transfers:'<path d="M4 7h16m-5-5 5 5-5 5M20 17H4m5-5-5 5 5 5"/>',league:'<path d="M8 3h8v7a4 4 0 0 1-8 0ZM8 5H4v3a4 4 0 0 0 4 4m8-7h4v3a4 4 0 0 1-4 4M12 14v6m-5 1h10"/>',training:'<path d="m4 16 5-5 4 3 7-9M15 5h5v5"/>',finances:'<rect x="3" y="5" width="18" height="14" rx="2"/><circle cx="12" cy="12" r="3"/><path d="M6 12h1m10 0h1"/>',editor:'<path d="m15 4 5 5M4 20l4-1L21 6l-4-4L4 15ZM4 20l-1 1"/>',save:'<path d="M5 3h12l4 4v14H3V3ZM7 3v6h10V3M7 21v-8h10v8"/>',import:'<path d="M12 3v12m-4-4 4 4 4-4M4 16v5h16v-5"/>',play:'<path d="m8 4 13 8-13 8Z"/>',pause:'<path d="M7 4v16M17 4v16"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',home:'<path d="m3 10 9-7 9 7v11h-7v-8h-4v8H3Z"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 8a3 3 0 0 1 6 0c0 2-3 2-3 5m0 3v1"/>',news:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M7 8h10M7 12h10M7 16h6"/>',chevron:'<path d="m9 5 7 7-7 7"/>'};
  return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]||paths.dashboard}</svg>`;
};
let toastTimeout;
export function toast(message,error=false){const el=document.querySelector('#toast');el.textContent=message;el.className=`show ${error?'error':''}`;clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>el.className='',error?7000:4000);}
export function showModal(titleText,body,footer='') {const d=document.querySelector('#modal');d.innerHTML=`<div class="modal-head"><h2>${esc(titleText)}</h2><button class="close" data-close aria-label="Close dialog">×</button></div>${body}${footer}`;if(!d.open)d.showModal();d.querySelector('[data-close]').onclick=()=>d.close();return d;}
export function confirmAction(titleText,text,action){const d=showModal(titleText,`<div class="modal-body"><p>${esc(text)}</p></div>`,`<div class="modal-footer"><button class="btn" data-cancel>Cancel</button><button class="btn danger" data-confirm>Confirm</button></div>`);d.querySelector('[data-cancel]').onclick=()=>d.close();d.querySelector('[data-confirm]').onclick=()=>{try{action();d.close();}catch(e){toast(e.message,true);}};}
export function download(name,text,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function pickFile(accept,callback){const el=document.querySelector('#file-input');el.accept=accept;el.value='';el.onchange=async()=>{const file=el.files[0];if(!file)return;try{if(file.size>10_000_000)throw Error('Maximum file size is 10 MB.');await callback(await file.text(),file.name);}catch(e){toast(e.message,true);}};el.click();}
export function errorsHTML(errors){return `<div class="error-list" role="alert">${esc(errors.slice(0,30).join('\n'))}${errors.length>30?`\n… and ${errors.length-30} more errors.`:''}</div>`;}
